import Sharesdisplay from "../components/Sharesdisplay";

import "../styles.css";

export default function ASXETFS() {
    
    const Symbols = ["A200.AX","ILC.AX","INIF.AX","IOZ.AX","MVW.AX","QOZ.AX","SFY.AX","STW.AX","VAS.AX","VLC.AX","EX20.AX","IMPQ.AX","ISO.AX","KSM.AX","MVE.AX","MVS.AX","SSO.AX","VSO.AX","ATEC.AX","MVB.AX","MVR.AX","OZF.AX","OZR.AX","QFN.AX","QRE.AX","AASF.AX","AUMF.AX","AUST.AX","BBOZ.AX","BEAR.AX","DVDY.AX","E200.AX","EIGA.AX","EINC.AX","FAIR.AX","GEAR.AX","GRNV.AX","HVST.AX","IHD.AX","IIGF.AX","INES.AX","MVOL.AX","RARI.AX","RDV.AX","SELF.AX","SMLL.AX","SWTZ.AX","SYI.AX","VETH.AX","VHY.AX","YMAX.AX","ZYAU.AX","IHOO.AX","IOO.AX","IVE.AX","IWLD.AX","VEU.AX","VGS.AX","WXOZ.AX","ACDC.AX","ASIA.AX","BNKS.AX","CLDD.AX","CLNE.AX","CNEW.AX","CURE.AX","DRUG.AX","ESPO.AX","FANG.AX","FOOD.AX","FUEL.AX","GDX.AX","HACK.AX","HLTH.AX","HNDQ.AX","IXI.AX","IXJ.AX","MNRS.AX","RBTZ.AX","ROBO.AX","TECH.AX","VISM.AX","ADEF.AX","AGX1.AX","BBUS.AX","EMMG.AX","ESGI.AX","ETHI.AX","ERTH.AX","FEMX.AX","GGUS.AX","GOAT.AX","HETH.AX","HQLT.AX","HYGG.AX","IHWL.AX","INCM.AX","LNAS.AX","LPGD.AX","MAET.AX","MGOC.AX","MHG.AX","MKAX.AX","MOAT.AX","MOGL.AX","MSTR.AX","PIXX.AX","QHAL.AX","QLTY.AX","QMIX.AX","QSML.AX","QUAL.AX","SNAS.AX","UMAX.AX","VESG.AX","VGAD.AX","VGMF.AX","VLUE.AX","VMIN.AX","VVLU.AX","WCMQ.AX","WDIV.AX","WRLD.AX","WXHG.AX","ZYUS.AX","QUS.AX","WDMF.AX","WVOL.AX","EMKT.AX","IEM.AX","VGE.AX","WEMG.AX","IAA.AX","PAXX.AX","VAE.AX","CETF.AX","IZZ.AX","ESTX.AX","HEUR.AX","IEU.AX","VEQ.AX","HJPN.AX","IJP.AX","IKO.AX","F100.AX","IHVV.AX","IJH.AX","IJR.AX","IVV.AX","NDQ.AX","SPY.AX","VTS.AX","IIND.AX","NDIA.AX","IFRA.AX","MICH.AX","VBLD.AX","MVA.AX","RINC.AX","SLF.AX","VAP.AX","DJRE.AX","REIT.AX","AUDS.AX","EEU.AX","POU.AX","USD.AX","YANK.AX","AGVT.AX","BNDS.AX","BOND.AX","CRED.AX","FLOT.AX","GOVT.AX","HBRD.AX","IAF.AX","ICOR.AX","IGB.AX","ILB.AX","IYLD.AX","PLUS.AX","QPON.AX","RCB.AX","RGB.AX","RSM.AX","SUBD.AX","VACF.AX","VAF.AX","VGB.AX","XARO.AX","EBND.AX","GBND.AX","GGOV.AX","IHCB.AX","IHEB.AX","IHHY.AX","VBND.AX","VCF.AX","VEFI.AX","VIF.AX","AAA.AX","BILL.AX","ISEC.AX","DBBF.AX","DGGF.AX","DHHF.AX","DZZF.AX","GROW.AX","VDBA.AX","VDCO.AX","VDGR.AX","VDHG.AX","ETPMAG.AX","ETPMPD.AX","ETPMPM.AX","ETPMPT.AX","GOLD.AX","OOO.AX","PMGOLD.AX","QAU"];
    
    return (
      <div>
        {Symbols.map((Symbol) => <Sharesdisplay Symbol={Symbol} />)}
      </div>
    );
}





