var express = require("express");
var router = express.Router();

router.get("/IBM", function(req, res, next) {
    res.send( {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines Corporation",
        "Description": "International Business Machines Corporation provides integrated solutions and services worldwide. Its Cloud & Cognitive Software segment offers software for vertical and domain-specific solutions in health, financial services, supply chain, and asset management, weather, and security software and services application areas; and customer information control system and storage, and analytics and integration software solutions to support client mission critical on-premise workloads in banking, airline, and retail industries. It also offers middleware and data platform software, including Red Hat that enables the operation of clients' hybrid multi-cloud environments; and Cloud Paks, WebSphere distributed, and analytics platform software, such as DB2 distributed, information integration, and enterprise content management, as well as IoT, Blockchain and AI/Watson platforms. The company's Global Business Services segment offers business consulting services; system integration, application management, maintenance, and support services for packaged software; and finance, procurement, talent and engagement, and industry-specific business process outsourcing services. Its Global Technology Services segment provides IT infrastructure and platform services; and project, managed, outsourcing, and cloud-delivered services for enterprise IT infrastructure environments; and IT infrastructure support services. The company's Systems segment offers servers for businesses, cloud service providers, and scientific computing organizations; data storage products and solutions; and z/OS, an enterprise operating system, as well as Linux. Its Global Financing segment provides lease, installment payment, loan financing, short-term working capital financing, and remanufacturing and remarketing services. The company was formerly known as Computing-Tabulating-Recording Co. The company was incorporated in 1911 and is headquartered in Armonk, New York.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "Technology",
        "Industry": "Information Technology Services",
        "Address": "One New Orchard Road, Armonk, NY, United States, 10504",
        "FullTimeEmployees": "345900",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2021-03-31",
        "MarketCapitalization": "128275415040",
        "EBITDA": "16407000064",
        "PERatio": "24.005",
        "PEGRatio": "1.3856",
        "BookValue": "23.936",
        "DividendPerShare": "4.89",
        "DividendYield": "0.0354",
        "EPS": "5.98",
        "RevenuePerShareTTM": "82.739",
        "ProfitMargin": "0.0728",
        "OperatingMarginTTM": "0.1311",
        "ReturnOnAssetsTTM": "0.04",
        "ReturnOnEquityTTM": "0.2536",
        "RevenueTTM": "73782001664",
        "GrossProfitTTM": "35575000000",
        "DilutedEPSTTM": "5.98",
        "QuarterlyEarningsGrowthYOY": "-0.192",
        "QuarterlyRevenueGrowthYOY": "0.009",
        "AnalystTargetPrice": "140.72",
        "TrailingPE": "24.005",
        "ForwardPE": "12.1655",
        "PriceToSalesRatioTTM": "1.6211",
        "PriceToBookRatio": "5.7754",
        "EVToRevenue": "2.3259",
        "EVToEBITDA": "12.6502",
        "Beta": "1.225",
        "52WeekHigh": "139.77",
        "52WeekLow": "103.0292",
        "50DayMovingAverage": "130.628",
        "200DayMovingAverage": "124.0923",
        "SharesOutstanding": "893593984",
        "SharesFloat": "891973648",
        "SharesShort": "27009286",
        "SharesShortPriorMonth": "30005072",
        "ShortRatio": "4.85",
        "ShortPercentOutstanding": "0.03",
        "ShortPercentFloat": "0.0303",
        "PercentInsiders": "0.132",
        "PercentInstitutions": "58.2",
        "ForwardAnnualDividendRate": "6.52",
        "ForwardAnnualDividendYield": "0.049",
        "PayoutRatio": "0.6245",
        "DividendDate": "2021-03-10",
        "ExDividendDate": "2021-02-09",
        "LastSplitFactor": "2:1",
        "LastSplitDate": "1999-05-27"
    } );
});

router.get("/AMD", function(req, res, next) {
    res.send( {
        "Symbol": "AMD",
        "AssetType": "Common Stock",
        "Name": "Advanced Micro Devices, Inc",
        "Description": "Advanced Micro Devices, Inc. operates as a semiconductor company worldwide. The company operates in two segments, Computing and Graphics; and Enterprise, Embedded and Semi-Custom. Its products include x86 microprocessors as an accelerated processing unit, chipsets, discrete and integrated graphics processing units (GPUs), data center and professional GPUs, and development services; and server and embedded processors, and semi-custom System-on-Chip (SoC) products, development services, and technology for game consoles. The company provides x86 microprocessors for desktop PCs under the AMD Ryzen, AMD Ryzen PRO, Ryzen, Threadripper, AMD A-Series, AMD FX, AMD Athlon, AMD Athlon PRO, and AMD Pro A-Series processors brands; microprocessors for notebook and 2-in-1s under the AMD Ryzen, AMD A-Series, AMD Athlon, AMD Ryzen PRO, AMD Athlon PRO, and AMD Pro A-Series processors brands; microprocessors for servers under the AMD EPYC and AMD Opteron brands; and chipsets under the AMD trademark. It also offers discrete GPUs for desktop and notebook PCs under the AMD Radeon graphics and AMD Embedded Radeon brands; professional graphics products under the AMD Radeon Pro and AMD FirePro graphics brands; and Radeon Instinct and AMD Instinct accelerators for servers. In addition, the company provides embedded processor solutions under the AMD Opteron, AMD Athlon, AMD Geode, AMD Ryzen, AMD EPYC, AMD R-Series, and G-Series processors brands; and customer-specific solutions based on AMD CPU, GPU, and multi-media technologies, as well as semi-custom SoC products. It serves original equipment manufacturers, public cloud service providers, original design manufacturers, system integrators, independent distributors, online retailers, and add-in-board manufacturers through its direct sales force, independent distributors, and sales representatives. Advanced Micro Devices, Inc. was founded in 1969 and is headquartered in Santa Clara, California.",
        "CIK": "2488",
        "Exchange": "NASDAQ",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Address": "2485 Augustine Drive, Santa Clara, CA, United States, 95054",
        "FullTimeEmployees": "12600",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2020-12-31",
        "MarketCapitalization": "99124330496",
        "EBITDA": "1680999936",
        "PERatio": "39.5397",
        "PEGRatio": "1.4913",
        "BookValue": "4.82",
        "DividendPerShare": "None",
        "DividendYield": "0",
        "EPS": "2.064",
        "RevenuePerShareTTM": "8.246",
        "ProfitMargin": "0.255",
        "OperatingMarginTTM": "0.1402",
        "ReturnOnAssetsTTM": "0.1142",
        "ReturnOnEquityTTM": "0.5748",
        "RevenueTTM": "9763000320",
        "GrossProfitTTM": "4347000000",
        "DilutedEPSTTM": "2.064",
        "QuarterlyEarningsGrowthYOY": "9.138",
        "QuarterlyRevenueGrowthYOY": "0.525",
        "AnalystTargetPrice": "102.4",
        "TrailingPE": "39.5397",
        "ForwardPE": "41.4938",
        "PriceToSalesRatioTTM": "9.8002",
        "PriceToBookRatio": "16.4951",
        "EVToRevenue": "9.6818",
        "EVToEBITDA": "56.3979",
        "Beta": "2.0557",
        "52WeekHigh": "99.23",
        "52WeekLow": "48.42",
        "50DayMovingAverage": "79.8334",
        "200DayMovingAverage": "85.7616",
        "SharesOutstanding": "1211320064",
        "SharesFloat": "1204545292",
        "SharesShort": "81563521",
        "SharesShortPriorMonth": "83627064",
        "ShortRatio": "1.86",
        "ShortPercentOutstanding": "0.07",
        "ShortPercentFloat": "0.0675",
        "PercentInsiders": "0.576",
        "PercentInstitutions": "77.423",
        "ForwardAnnualDividendRate": "0",
        "ForwardAnnualDividendYield": "0",
        "PayoutRatio": "0",
        "DividendDate": "None",
        "ExDividendDate": "1995-04-27",
        "LastSplitFactor": "2:1",
        "LastSplitDate": "2000-08-22"
    } );
});

router.get("/NVDA", function(req, res, next) {
    res.send( {
        "Symbol": "NVDA",
        "AssetType": "Common Stock",
        "Name": "NVIDIA Corporation",
        "Description": "NVIDIA Corporation operates as a visual computing company worldwide. It operates in two segments, Graphics and Compute & Networking. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise design; GRID software for cloud-based visual and virtual computing; and automotive platforms for infotainment systems. The Compute & Networking segment offers Data Center platforms and systems for AI, HPC, and accelerated computing; Mellanox networking and interconnect solutions; automotive AI Cockpit, autonomous driving development agreements, and autonomous vehicle solutions; and Jetson for robotics and other embedded platforms. The company's products are used in gaming, professional visualization, datacenter, and automotive markets. NVIDIA Corporation sells its products to original equipment manufacturers, original device manufacturers, system builders, add-in board manufacturers, retailers/distributors, Internet and cloud service providers, automotive manufacturers and tier-1 automotive suppliers, mapping companies, start-ups, and other ecosystem participants. NVIDIA Corporation was founded in 1993 and is headquartered in Santa Clara, California.",
        "CIK": "1045810",
        "Exchange": "NASDAQ",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Address": "2788 San Tomas Expressway, Santa Clara, CA, United States, 95051",
        "FullTimeEmployees": "18975",
        "FiscalYearEnd": "January",
        "LatestQuarter": "2021-01-31",
        "MarketCapitalization": "381504454656",
        "EBITDA": "5818999808",
        "PERatio": "88.0724",
        "PEGRatio": "3.94",
        "BookValue": "27.247",
        "DividendPerShare": "0.64",
        "DividendYield": "0.0011",
        "EPS": "6.9",
        "RevenuePerShareTTM": "27.026",
        "ProfitMargin": "0.2598",
        "OperatingMarginTTM": "0.2831",
        "ReturnOnAssetsTTM": "0.128",
        "ReturnOnEquityTTM": "0.2978",
        "RevenueTTM": "16675000320",
        "GrossProfitTTM": "10557000000",
        "DilutedEPSTTM": "6.9",
        "QuarterlyEarningsGrowthYOY": "0.515",
        "QuarterlyRevenueGrowthYOY": "0.611",
        "AnalystTargetPrice": "661.61",
        "TrailingPE": "88.0724",
        "ForwardPE": "46.0829",
        "PriceToSalesRatioTTM": "23.9713",
        "PriceToBookRatio": "23.3606",
        "EVToRevenue": "23.4355",
        "EVToEBITDA": "68.6675",
        "Beta": "1.3756",
        "52WeekHigh": "648.57",
        "52WeekLow": "280.2085",
        "50DayMovingAverage": "543.518",
        "200DayMovingAverage": "542.1523",
        "SharesOutstanding": "619000000",
        "SharesFloat": "594573800",
        "SharesShort": "6210288",
        "SharesShortPriorMonth": "6773000",
        "ShortRatio": "0.75",
        "ShortPercentOutstanding": "0.01",
        "ShortPercentFloat": "0.0104",
        "PercentInsiders": "4.2",
        "PercentInstitutions": "68.634",
        "ForwardAnnualDividendRate": "0.64",
        "ForwardAnnualDividendYield": "0.001",
        "PayoutRatio": "0.0641",
        "DividendDate": "2021-03-31",
        "ExDividendDate": "2021-03-09",
        "LastSplitFactor": "3:2",
        "LastSplitDate": "2007-09-11"
    } );
});

router.get("/AAPL", function(req, res, next) {
    res.send( {
        "Symbol": "AAPL",
        "AssetType": "Common Stock",
        "Name": "Apple Inc",
        "Description": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.",
        "CIK": "320193",
        "Exchange": "NASDAQ",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "Technology",
        "Industry": "Consumer Electronics",
        "Address": "One Apple Park Way, Cupertino, CA, United States, 95014",
        "FullTimeEmployees": "147000",
        "FiscalYearEnd": "September",
        "LatestQuarter": "2020-12-31",
        "MarketCapitalization": "2235251556352",
        "EBITDA": "85159002112",
        "PERatio": "36.112",
        "PEGRatio": "2.9242",
        "BookValue": "3.936",
        "DividendPerShare": "0.807",
        "DividendYield": "0.0061",
        "EPS": "3.687",
        "RevenuePerShareTTM": "17.13",
        "ProfitMargin": "0.2174",
        "OperatingMarginTTM": "0.2525",
        "ReturnOnAssetsTTM": "0.1336",
        "ReturnOnEquityTTM": "0.8209",
        "RevenueTTM": "294135005184",
        "GrossProfitTTM": "104956000000",
        "DilutedEPSTTM": "3.687",
        "QuarterlyEarningsGrowthYOY": "0.344",
        "QuarterlyRevenueGrowthYOY": "0.214",
        "AnalystTargetPrice": "152.06",
        "TrailingPE": "36.112",
        "ForwardPE": "30.7692",
        "PriceToSalesRatioTTM": "7.9547",
        "PriceToBookRatio": "34.1826",
        "EVToRevenue": "7.8159",
        "EVToEBITDA": "26.0106",
        "Beta": "1.2195",
        "52WeekHigh": "144.8735",
        "52WeekLow": "68.7173",
        "50DayMovingAverage": "125.0266",
        "200DayMovingAverage": "124.9905",
        "SharesOutstanding": "16788100096",
        "SharesFloat": "16770636380",
        "SharesShort": "101484668",
        "SharesShortPriorMonth": "107011007",
        "ShortRatio": "0.88",
        "ShortPercentOutstanding": "0.01",
        "ShortPercentFloat": "0.006",
        "PercentInsiders": "0.076",
        "PercentInstitutions": "59.807",
        "ForwardAnnualDividendRate": "0.82",
        "ForwardAnnualDividendYield": "0.0062",
        "PayoutRatio": "0.2216",
        "DividendDate": "2021-02-11",
        "ExDividendDate": "2021-02-05",
        "LastSplitFactor": "4:1",
        "LastSplitDate": "2020-08-31"
    } );
});

router.get("/WES", function(req, res, next) {
    res.send( {
        "Symbol": "WES",
        "AssetType": "Common Stock",
        "Name": "Western Midstream Partners, LP",
        "Description": "Western Midstream Partners, LP, together with its subsidiaries, acquire, own, develop, and operate midstream assets primarily in the United States. It is involved in gathering, compressing, treating, processing, and transporting of natural gas; gathering, stabilizing, and transporting of condensate, natural gas liquids, and crude oil; and gathering and disposing of produced water. The company also buys and sells natural gas, NGLs, and condensate. Western Midstream Holdings, LLC operates as the general partner of the company. The company was formerly known as Western Gas Equity Partners, LP and changed its name to Western Midstream Partners, LP in February 2019. The company was founded in 2007 and is headquartered in The Woodlands, Texas. Western Midstream Partners, LP operates as a subsidiary of Occidental Petroleum Corporation.",
        "CIK": "1423902",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "Energy",
        "Industry": "Oil & Gas Midstream",
        "Address": "9950 Woodloch Forest Drive, The Woodlands, TX, United States, 77380",
        "FullTimeEmployees": "1045",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2020-12-31",
        "MarketCapitalization": "7939051520",
        "EBITDA": "1794590976",
        "PERatio": "16.2331",
        "PEGRatio": "5.48",
        "BookValue": "6.714",
        "DividendPerShare": "1.244",
        "DividendYield": "0.0651",
        "EPS": "1.184",
        "RevenuePerShareTTM": "6.366",
        "ProfitMargin": "0.1861",
        "OperatingMarginTTM": "0.4647",
        "ReturnOnAssetsTTM": "0.0666",
        "ReturnOnEquityTTM": "0.1656",
        "RevenueTTM": "2772592128",
        "GrossProfitTTM": "2003630000",
        "DilutedEPSTTM": "1.184",
        "QuarterlyEarningsGrowthYOY": "-0.002",
        "QuarterlyRevenueGrowthYOY": "-0.105",
        "AnalystTargetPrice": "21.87",
        "TrailingPE": "16.2331",
        "ForwardPE": "7.57",
        "PriceToSalesRatioTTM": "3.0146",
        "PriceToBookRatio": "2.8708",
        "EVToRevenue": "5.5314",
        "EVToEBITDA": "11.1094",
        "Beta": "3.8671",
        "52WeekHigh": "20.9",
        "52WeekLow": "5.7729",
        "50DayMovingAverage": "18.9289",
        "200DayMovingAverage": "14.6653",
        "SharesOutstanding": "413062016",
        "SharesFloat": "210069523",
        "SharesShort": "4488089",
        "SharesShortPriorMonth": "3337916",
        "ShortRatio": "1.7",
        "ShortPercentOutstanding": "0.01",
        "ShortPercentFloat": "0.0226",
        "PercentInsiders": "49.342",
        "PercentInstitutions": "38.946",
        "ForwardAnnualDividendRate": "1.24",
        "ForwardAnnualDividendYield": "0.0651",
        "PayoutRatio": "0.484",
        "DividendDate": "2021-02-12",
        "ExDividendDate": "2021-01-29",
        "LastSplitFactor": "10:9",
        "LastSplitDate": "2014-11-26"
    } );
});

module.exports = router;